---
- project:
    check:
      jobs:
        - stx-puppet-linters
    gate:
      jobs:
        - stx-puppet-linters

- job:
    name: stx-puppet-linters
    parent: openstack-tox-linters
    description: |
      Run linters for stx-puppet
    pre-run: playbooks/tox-puppet-lint/pre.yaml

